# .github/workflows/ci.yml
name: CI Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Exécuter un script shell
        run: echo "Hello, GitHub Actions!"
